-- Create Database
CREATE DATABASE IF NOT EXISTS products_db;
USE products_db;

-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(191) DEFAULT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role ENUM('user', 'admin') DEFAULT 'user',
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create Products Table
CREATE TABLE IF NOT EXISTS products (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Product_Name VARCHAR(255) NOT NULL,
    Category VARCHAR(100),
    Size VARCHAR(50),
    Description TEXT,
    Fabrication VARCHAR(100),
    Construction VARCHAR(100),
    GSM VARCHAR(50),
    Finishes VARCHAR(100),
    Color VARCHAR(50),
    Buyer VARCHAR(100),
    Style VARCHAR(100),
    Tags VARCHAR(255),
    Main_Image VARCHAR(255),
    Image1 VARCHAR(255),
    Image2 VARCHAR(255),
    Image3 VARCHAR(255),
    Image4 VARCHAR(255),
    Product_URL VARCHAR(255) NOT NULL UNIQUE,
    Price DECIMAL(10,2),
    Tag VARCHAR(255),
    Created_By INT,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Created_By) REFERENCES users(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert Default Admin User
-- Password: admin123 (hashed using password_hash with PASSWORD_DEFAULT)
INSERT INTO users (Username, Email, Password, Role) VALUES 
('admin', 'admin@til.local', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin'),
('testuser', 'testuser@til.local', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'user');

-- Insert Sample Products
INSERT INTO products (Product_Name, Category, Size, Description, Fabrication, Construction, GSM, Finishes, Color, Buyer, Style, Tags, Main_Image, Image1, Image2, Image3, Image4, Product_URL, Price, Tag, Created_By) VALUES
(
    'Premium Cotton T-Shirt',
    'Apparel',
    'M, L, XL',
    'High-quality 100% cotton t-shirt with reinforced stitching. Perfect for casual wear, this comfortable and breathable fabric ensures all-day comfort.',
    '100% Cotton',
    'Single Jersey',
    '180',
    'Bio-washed, Pre-shrunk',
    'Navy Blue',
    'H&M',
    'Basic Crew Neck',
    'cotton, t-shirt, casual, comfortable',
    'https://unsplash.com/photos/4mLKBKMPoHo/download?force=true&w=1200',
         'https://unsplash.com/photos/5E5N49RWtbA/download?force=true&w=1200',
         'https://unsplash.com/photos/mp0bgAAfoUs/download?force=true&w=1200',
         'https://unsplash.com/photos/RiDxDgHg7pw/download?force=true&w=1200',
         'https://unsplash.com/photos/yCdPU73kGSc/download?force=true&w=1200',
         'https://unsplash.com/photos/DgXIq5tTUqY/download?force=true&w=1200',
    24.99,
    'New Arrival',
    1
),
(
    'Denim Slim Fit Jeans',
    'Apparel',
    '30, 32, 34, 36',
    'Classic slim fit denim jeans with a modern cut. Made from stretch denim for maximum comfort and mobility. Features 5-pocket styling.',
    'Cotton Denim Blend',
    'Twill Weave',
    '320',
    'Stone Washed, Whiskers',
    'Dark Blue',
    'Levi\'s',
    'Slim Fit',
    'jeans, denim, pants, casual',
    'https://unsplash.com/photos/cyZiG7-Ng3w/download?force=true&w=1200',
         'https://unsplash.com/photos/Lks7vei-eAg/download?force=true&w=1200',
         'https://unsplash.com/photos/SJvDxw0azqw/download?force=true&w=1200',
         'https://unsplash.com/photos/qqRGHREFJJc/download?force=true&w=1200',
         'https://unsplash.com/photos/R3LcfTvcGWY/download?force=true&w=1200',
         'https://unsplash.com/photos/90WdFgbf59w/download?force=true&w=1200',
    49.99,
    'Bestseller',
    1
),
(
    'Formal Dress Shirt',
    'Apparel',
    'S, M, L, XL',
    'Elegant formal shirt crafted from premium cotton fabric. Features button-down collar and adjustable cuffs. Ideal for business and formal occasions.',
    'Cotton Poplin',
    'Plain Weave',
    '120',
    'Wrinkle-free, Easy Iron',
    'White',
    'Brooks Brothers',
    'Regular Fit',
    'shirt, formal, office, business',
    'https://unsplash.com/photos/xoEb3kS_YoM/download?force=true&w=1200',
         'https://unsplash.com/photos/T7K4aEPoGGk/download?force=true&w=1200',
         'https://unsplash.com/photos/6anudmpILw4/download?force=true&w=1200',
         'https://unsplash.com/photos/Yc5sL5MCbEA/download?force=true&w=1200',
         'https://unsplash.com/photos/cYyqhdbJ9TI/download?force=true&w=1200',
         'https://unsplash.com/photos/OW5KP_Pj85Q/download?force=true&w=1200',
    39.99,
    'Professional',
    1
),
(
    'Athletic Performance Polo',
    'Apparel',
    'M, L, XL, XXL',
    'Moisture-wicking polo shirt designed for active lifestyles. Quick-dry fabric with UV protection. Perfect for sports and outdoor activities.',
    'Polyester Blend',
    'Pique Knit',
    '200',
    'Moisture-wicking, UV Protection',
    'Red',
    'Nike',
    'Athletic Fit',
    'polo, sports, athletic, performance',
    'https://unsplash.com/photos/3a5zGAfZnHY/download?force=true&w=1200',
         'https://unsplash.com/photos/jgWZM5TXnwE/download?force=true&w=1200',
         'https://unsplash.com/photos/FQgI8AD-BSg/download?force=true&w=1200',
         'https://unsplash.com/photos/VxrFNhSI9zk/download?force=true&w=1200',
         'https://unsplash.com/photos/LvSUaq_yhBY/download?force=true&w=1200',
         'https://unsplash.com/photos/Zb0hcV0nJFE/download?force=true&w=1200',
    34.99,
    'Sports Collection',
    1
),
(
    'Winter Wool Sweater',
    'Apparel',
    'S, M, L',
    'Cozy wool blend sweater perfect for cold weather. Features ribbed collar and cuffs with a classic cable knit pattern. Provides excellent warmth.',
    'Wool Blend',
    'Cable Knit',
    '450',
    'Soft-finish, Anti-pilling',
    'Charcoal Gray',
    'Zara',
    'Regular Fit',
    'sweater, winter, wool, warm',
    'https://unsplash.com/photos/msoFnF5ShDY/download?force=true&w=1200',
         'https://unsplash.com/photos/xPJYL0l5Ii8/download?force=true&w=1200',
         'https://unsplash.com/photos/OvW_Eh0KF10/download?force=true&w=1200',
         'https://unsplash.com/photos/XnC5eO2WFh8/download?force=true&w=1200',
         'https://unsplash.com/photos/MVGxDHj3c7o/download?force=true&w=1200',
         'https://unsplash.com/photos/hR535Mow9_E/download?force=true&w=1200',
    59.99,
    'Winter Collection',
    1
),
(
    'Casual Hooded Sweatshirt',
    'Apparel',
    'M, L, XL',
    'Comfortable hooded sweatshirt with kangaroo pocket. Made from soft cotton fleece blend. Perfect for everyday casual wear.',
    'Cotton Fleece',
    'French Terry',
    '280',
    'Brushed Inside',
    'Black',
    'Gap',
    'Relaxed Fit',
    'hoodie, sweatshirt, casual, comfort',
    'https://unsplash.com/photos/cyZiG7-Ng3w/download?force=true&w=1200',
         'https://unsplash.com/photos/WWesmHEgXDs/download?force=true&w=1200',
         'https://unsplash.com/photos/HRZUzoX1e6w/download?force=true&w=1200',
         'https://unsplash.com/photos/Y_aXcZ4VLqI/download?force=true&w=1200',
         'https://unsplash.com/photos/YWX9z_fcG0o/download?force=true&w=1200',
         'https://unsplash.com/photos/8lnbXtxFGZw/download?force=true&w=1200',
    44.99,
    'Everyday Wear',
    1
),
(
    'Linen Summer Shorts',
    'Apparel',
    '28, 30, 32, 34',
    'Lightweight linen shorts perfect for summer. Breathable fabric with elastic waistband and multiple pockets. Great for beach and casual wear.',
    'Linen Blend',
    'Plain Weave',
    '150',
    'Garment Dyed',
    'Khaki',
    'Uniqlo',
    'Loose Fit',
    'shorts, summer, linen, casual',
    'https://unsplash.com/photos/xvU9w66qFoU/download?force=true&w=1200',
         'summer, shorts, linen, casual',
         'https://unsplash.com/photos/EuDapbwpPmA/download?force=true&w=1200',
         'https://unsplash.com/photos/vCF5sB7QecM/download?force=true&w=1200',
         'https://unsplash.com/photos/iMdsjoiftZo/download?force=true&w=1200',
         'https://unsplash.com/photos/zWTGZOe3YBo/download?force=true&w=1200',
         'https://unsplash.com/photos/H7B-M3HQbgE/download?force=true&w=1200',
    'Summer Collection',
    1
);

-- Note: Default password for all sample users is 'admin123'
-- Please change passwords after initial setup
